### ISSUE TITLE
Returning an ActionReducerMap

### ISSUE THREAD

**Issue by st-clair-clarke** [KwintenP/combine-reducers-enhanced#1]
Hi,
I have been looking at this project and experimenting some. I am currently using ngrx 4 and angular 4 enveronment.

How can I renturn an ngrx4  ActionReducerMap<IClerking> type using your fuction

`function combineReducersEnhanced(reducers: any): Function;`

Cheers

PS: casting the return value of the function does not work.

**Comment by KwintenP** [comment]
Hi, 

Unfortunately I didn't have the time yet to update this lib to be angular 4 compliant. I'll fix this asap. Thanks for reporting!

**Comment by st-clair-clarke** [comment]
Thanks KwintenP. Looking forward to your angular4 version.

Cheers

**Comment by leerenold** [comment]
Any update on this ? Thanx in advance.

**Comment by KwintenP** [comment]
I totally forgot to do this. My apologies.

I released a new version (0.0.5) that can allows you to pass a second parameter to the function. If you pass false, you'll get back an object that matches the ActionMapReducer you need for @ngrx/store.

`const enhancedRootReducer: ActionReducerMap = combineReducersEnhanced(rootReducer, false);`

(see the README.md for a complete example).
